# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
host: 0.0.0.0
title: Freeside
email: admin@freeside.co.uk
description: >- # this means to ignore newlines until "baseurl:"
    Freeside is a student run project at the University of Hull (http://www.hull.ac.uk/) which offers free (in both free beer and free speech terms) Unix, Open and Alternative computing services to the student population 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://freeside.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: FreesideHull
github_username:  FreesideHull

discourse_url: "https://forums.freeside.co.uk"


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Author details.
kieran_coldron:
    name: Kieran Coldron
    email: kieran@coldron.com
    web: http://kieran.coldron.com
harryg:
    name: Harry Gwinnell

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
